### ISSUE TITLE
Problems installing Rate4Site

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/ConSurf#10]
- [ ] The README must clearly indicate which version to install from the webpage: http://www.tau.ac.il/~itaymay/cp/rate4site.html
- [ ] So far I installed locally the version  ftp://rostlab.org/rate4site (3.0) -- I don't see a way to install _rate4siteSLOW_

**Comment by GrimSmiler** [comment]
I was able to download version 3.2 
[Uploading rate4site.3.2.source.zip…](Use this)

to build the fast version - just run:

```
cd rate4site.3.2.source/sourceMar09/
make
```

to build the slow version - just run:

```
cd rate4site.3.2.source/sourceMar09/
mv Makefile Makefile_fast
mv Makefile_slow Makefile
make
```

should do the trick
