### ISSUE TITLE
Write example files for demonstration

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/ConSurf#11]
- [x] Write all necessary sample files under folder `example/` to be able to run the examples. For instance, have a sample file for `MY_PDB_FILE.pdb`, etc.
- [x] All examples listed in the README should be runnable with no or minimal changes from the user
- [x] Is this fine? `-BlastFile /<path_to_dir>/ConSurf/output/_A.protein_query.blast` should it include the prefix `1lk2` ?
- [x] Shouldn't be the `--workdir` the `example` folder?
- [x] At the moment in your sample script I see 4 different folders, `example`, `output`, `workdir`, and `output_test` -- Are all necessary? Can not some of them be the same? See:

```
consurf -PDB /<path_to_dir>/ConSurf/example/1lk2.pdb -CHAIN A -Out_Dir /<path_to_dir>/ConSurf/output_test/ -m --workdir /<path_to_dir>/ConSurf/workdir -BlastFile /<path_to_dir>/ConSurf/output/_A.protein_query.blast
```
- [x] Specify in README example that the workdir indeed must have the mentioned .fasta file (as mentioned in the presentation)

**Comment by GrimSmiler** [comment]
Understood. For right now only the first works but blastpgp failes due to inability to find the DB. WOrking on it.

**Comment by juanmirocks** [comment]
Now it's working, right? Did you write the sample files? If so, please check the checkmarks and close issue.

**Comment by GrimSmiler** [comment]
I have added a working command in the examples. User will have to specify the
dir to folders, rest should work.

or do You want a shell file with all the commands?

Best Regards, Ilya Migal On вт, янв. 19, 2016 at 11:17 AM, Juan Miguel Cejuela < notifications@github.com [notifications@github.com] > wrote:
Now it's working, right? Did you write the sample files? If so, please check the
checkmarks and close issue.

—
Reply to this email directly or view it on GitHub
[https://github.com/Rostlab/ConSurf/issues/11#issuecomment-172805042] .[https://github.com/notifications/beacon/AExpfZh6zNnR8k4TZcXfpu83uD9XXyr8ks5pbgTIgaJpZM4HFu-J.gif]

**Comment by juanmirocks** [comment]
@GrimSmiler I think you can assume `/<path_to_dir>/ConSurf/` (that is, the user is calling the script from the source folder) and therefore delete all those.

**Comment by GrimSmiler** [comment]
Understood. But, it seems that user has to specify the full path to the files
passed as arguments. I'll check that and prepare a better example

Best Regards, Ilya Migal On вт, янв. 19, 2016 at 12:00 PM, Juan Miguel Cejuela < notifications@github.com [notifications@github.com] > wrote:
@GrimSmiler [https://github.com/GrimSmiler] I think you can assume /<path_to_dir>/ConSurf/ (that is, the user is calling the script from the source folder) and therefore
delete all those.

—
Reply to this email directly or view it on GitHub
[https://github.com/Rostlab/ConSurf/issues/11#issuecomment-172818110] .[https://github.com/notifications/beacon/AExpfYCxkjrF1YtP9O9SYUkaAkfdfZW-ks5pbg7lgaJpZM4HFu-J.gif]

**Comment by GrimSmiler** [comment]
Shouldn't be the --workdir the example folder?

created workdir for this. User should use it as intermediate result storage (see --workdir argument description)

**Comment by GrimSmiler** [comment]
At the moment in your sample script I see 4 different folders, example, output, workdir, and output_test -- Are all necessary? Can not some of them be the same? See:

old folders are marked as `old_1lk2_<folder-name>`.
All folders that should be used now are example (stores all input data such as pdb files), output (where the results of the ConSurf execution will be stored) and workdir (intermediate results folder - see argument --workdir description)

**Comment by GrimSmiler** [comment]
Is this fine? -BlastFile /<path_to_dir>/ConSurf/output/_A.protein_query.blast should it include the prefix 1lk2 ?

fixed file naming in example and workdir folders

**Comment by juanmirocks** [comment]
Looks fine. You know better, but I understood previously that indeed you must include the prefix 1lk2, that is, the name of the pdb id

**Comment by GrimSmiler** [comment]
1lk2 in the beginning is just created by the ConSurf tool to mark for which protein it is performing the calculations. You can specify any file You want.

**Comment by GrimSmiler** [comment]
One of the examples doesn't actually work, but it is mentioned in the original README.
Should i delete it or make as "Currently not working/tested"?

**Comment by juanmirocks** [comment]
Rather put in the README only examples that work. Register those that do not work as issues.

**Comment by GrimSmiler** [comment]
> Write all necessary sample files under folder example/ to be able to run the examples. For instance, have a sample file for MY_PDB_FILE.pdb, etc.

In `example/` User can find all the necessary files to execute the ConSurf example.

> Specify in README example that the workdir indeed must have the mentioned .fasta file (as mentioned in the presentation)

Also added a "Requirements for successful run" section in HOWTO Run describing the current problem with `.blast` and `.fas` files with the link to the issues and the solution

**Comment by GrimSmiler** [comment]
> All examples listed in the README should be runnable with no or minimal changes from the user

All current examples in the Examples section are runnable. Rest of the examples are specified in the #15

**Comment by GrimSmiler** [comment]
May i close the issue?

**Comment by juanmirocks** [comment]
Great Ilya. I will verify everything within a week

**Comment by juanmirocks** [comment]
All fine :+1:
