### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/ConSurf#12]
Hey @GrimSmiler I don't know exactly what's the status of the tool. As with the current README.md documentation, I cannot install & run the tool myself without further instructions.

A few things that surprise me for example are:
- What is the runnable? `consurf` or `ConSurf.pl` or `ConSurf` ?
- You apparently created a vagrant image -- where is it? why don't you give instructions of it in the README.md ?

I know I'm reviewing the tool late, but we would need to have the method running before your presentation day. Contact me at any time for help and we can resolve all issues together.

You can find me on skype with same username

**Comment by GrimSmiler** [comment]
Hi!

Sorry for not writing you yesterday.

Tomorrow i'll continue with figuring out. I'll give you an update tomorrow.

Thanks for the help :) i'll add you in skype.

Best Regards, Ilya Migal On пт, янв. 15, 2016 at 3:12 PM, Juan Miguel Cejuela < notifications@github.com [notifications@github.com] > wrote:
Hey @GrimSmiler [https://github.com/GrimSmiler] I don't know exactly what's the status of the tool. As with the current
README.md documentation, I cannot install & run the tool myself without further
instructions.

A few things that surprise me for example are:
- What is the runnable? consurf or ConSurf.pl or ConSurf ?
- You apparently created a vagrant image -- where is it? why don't you give
  instructions of it in the README.md ?

I know I'm reviewing the tool late, but we would need to have the method running
before your presentation day. Contact me at any time for help and we can resolve
all issues together.

You can find me on skype with same username

**Comment by juanmirocks** [comment]
The issues seem to be solved.
