### ISSUE TITLE
Register in Elixir

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/ConSurf#13]
- [x] Register in Elixir, see instructions provided in last weekly tasks
- [x] Put link right under the header in README

**Comment by GrimSmiler** [comment]
https://bio.tools/tool/mytum.de/ConSurf/1.0.6

**Comment by GrimSmiler** [comment]
i think there might be a problem...
there is a link on Elixir from the official ConSurf organisation.
https://bio.tools/tool/Instruct/ConSurf/1

just to let you know
