### ISSUE TITLE
Got error when running  ./rate4site_build.sh

### ISSUE THREAD

**Issue by mullinyu** [Rostlab/ConSurf#19]
I'm trying to build rate4site by the following command on a Linux machine and got the following error.

~/software/ConSurf/3rd party software$ ./rate4site_build.sh
g++ -O3 -Wno-deprecated   -c -o errorMsg.o errorMsg.cpp
errorMsg.cpp: In static member function 'static void errorMsg::reportError(const std::vector<std::__cxx11::basic_string<char> >&, int)':
errorMsg.cpp:18:39: error: no match for 'operator!=' (operand types are 'std::ostream {aka std::basic_ostream<char>}' and 'std::ostream {aka std::basic_ostream<char>}')
   if (_errorOut != NULL && *_errorOut != cerr)  {
                            ~~~~~~~~~~~^~~~~~~
errorMsg.cpp:18:39: note: candidate: operator!=(int, int) <built-in>

Any ideas?

Thanks!

**Comment by juanmirocks** [comment]
Thank you very much for reporting the issue. I cannot help you but maybe somebody at @Rostlab/members can

**Comment by hypostulate** [comment]
I just tackled this error. It is due to new C++11 compiler error when implicitly converting streams to bool. See [this stackoverflow post](https://stackoverflow.com/questions/41871393/check-if-stream-reference-is-null-doesnt-compile-anymore). 

The .cpp code can be fixed by changing from instances of `if (stream == NULL)` to `if (stream.fail())` and from `if (stream != NULL)` to `if (stream)`.

**Comment by jushui** [comment]
Could you explain in detail ？I don't understand

**Comment by yazhinia** [comment]
How to resolve a similar error for this part `*_errorOut != cerr` in the if condition?

**Comment by sacdallago** [comment]
Unfortunately, we don't have the capacity to maintain this tool, and it's thus depecreated. If you are interested in protein conservation prediction, consider running VESPA instead: https://github.com/Rostlab/VESPA#step-2-conservation-prediction

**Comment by yazhinia** [comment]
Okay. Thank you for the quick response and for sharing the useful link.

**Comment by kingdavid72** [comment]
after C++11 standard we should use nullptr instead of NULL.
and  if (_errorOut != nullptr && !(_errorOut == &cerr))
we have to change compule more errors in .cpp files
