### ISSUE TITLE
User representation

### ISSUE THREAD

**Issue by GrimSmiler** [Rostlab/ConSurf#2]
Hi!

in consurf repo i found credentials of Guy Yachdav and someone who’s initials are gcelniker.
Any idea who that is?
I put just his initials for right now as they are, or should i try and find his email and full name?

Best Regards,
Ilya Migal

**Comment by GrimSmiler** [comment]
found. closing.

**Comment by gyachdav** [comment]
gcelnicker is Gershon Celniker
