### ISSUE TITLE
Perl. Problems loading config.

### ISSUE THREAD

**Issue by GrimSmiler** [Rostlab/ConSurf#5]
Hi all!

@jmcejuela , @gyachdav 
I have the following problem when trying to run ConSurf:

```
Can't call method "val" on an undefined value at ./consurf line 73.
BEGIN failed--compilation aborted at ./consurf line 74. 
```

Here is the code:
`$consurf_utildir = $config->val( 'consurf', 'consurf_utildir' );`

one reason for this error to happen might be that $config was not initialised properly. If anyone had a problem like this in the past or might have an idea what went wrong, I would be glad to hear it!

Best Regards,
Ilya

**Comment by GrimSmiler** [comment]
Can be fixed if installed correctly (issue about installation [here](https://github.com/Rostlab/ConSurf/issues/7))

After that ConSurf is available as a regular command:
`consurf <params>`
(stored in /usr/bin/local)

**Comment by juanmirocks** [comment]
Hi @GrimSmiler thanks so much for your great explanation today. I will fully check this project very soon. Write me anytime but forgive me if sometimes I don't answer fast enough.

**Comment by juanmirocks** [comment]
@GrimSmiler what's the status?

When I try to run myself that on OS X I get:

```
perl consurf
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at consurf line 36.
BEGIN failed--compilation aborted at consurf line 36.
```

**Comment by GrimSmiler** [comment]
Problem is caused by incorrect calling of ConSurf (see read me for instructions to install and run)
In any case user must install Perl and Perl Modules (see Readme)

I will close this, cause this is not relevant any more

**Comment by 893932098** [comment]
> Can't call method "val" on an undefined value at ./consurf line 73.
> BEGIN failed--compilation aborted at ./consurf line 74.

I also meet this problem, how to solve it.....
