### ISSUE TITLE
Installation. Automake. Compiling ConSurf returns an error. 

### ISSUE THREAD

**Issue by GrimSmiler** [Rostlab/ConSurf#7]
Problem:  
on `autoconf configure.ac` an error occurs:  

```
configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
```

Solution:
Use the following commands to compile ConSurf

```
$ aclocal
$ autoheader
$ automake --force-missing --add-missing
$ autoconf
```

**Comment by GrimSmiler** [comment]
Might now work actually because in README it says to run `perl consurf.pl ...`.
running this command from consurf folder returns another error.
And i am not sure if you even need to compile this thing.

**Comment by juanmirocks** [comment]
@GrimSmiler hey -- sorry for my big delay in reviewing all this but now I am into it.

Is everything working now? If not, what's the most important missing part?

I will write a few corrections and tasks here and there.

**Comment by juanmirocks** [comment]
@GrimSmiler the important thing is, what is needed for a _current user_ to install & run the tool successfully ?

**Comment by GrimSmiler** [comment]
I have a list. I will put it into the Installation manual later on

**Comment by GrimSmiler** [comment]
I guess the cause of confusion is bad upkeep of the original readme.

Consurf seems to work if the user executes the commands from the first comment + the configure & sudo make & sudo make install.

I will change the README to avoid confusion in the future
