### ISSUE TITLE
Blastpgp. Blastpgp does not find the files specified

### ISSUE THREAD

**Issue by GrimSmiler** [Rostlab/ConSurf#8]
Hi @gyachdav !

I found a small issue, maybe You could shed some light on it.

when i run a command:

```
sudo consurf -PDB /vagrant/ConSurf-develop/example/1lk2.pdb -CHAIN A -Out_Dir /vagrant/ConSurf-develop/output_test/ -m
```

i get the following output

```
ConSurf Version 1.0.6
====================================
Process Started at 12:13:54

Output files could be found in output directory: /vagrant/ConSurf-develop/output_test//
[blastpgp] ERROR: No argument value given for Database

run_blast : run of blast fail. /tmp/mCYRl6c35s//1lk2_A.protein_query.blast is zero or not exists
```

Do You know what could be the reason?
I guess balstpgp tries to create something in tmp folder, but it does not have any permissions.
Running the same some command using `sudo -i` returns the same error.

Best Regards,
Ilya Migal

**Comment by gyachdav** [comment]
Does /vagrant/ConSurf-develop/example/1lk2pdb exist? Is it a complete pdb file?  Read the error message and try to see why it didn't work for this specific instance.

**Comment by gyachdav** [comment]
Please do not assign issues to me. I am not involved with this course.

**Comment by GrimSmiler** [comment]
@gyachdav , sorry. won't do it again. the file does exist, it is also in the repo. gonna try a new file, see if it works. 

Thanks for the help!

**Comment by juanmirocks** [comment]
@GrimSmiler please do not assign to Guy. Just assign to me.

**Comment by juanmirocks** [comment]
@GrimSmiler any updates on this one?

**Comment by GrimSmiler** [comment]
Update:

Problem is caused by the following code in the file [consurf](https://github.com/Rostlab/ConSurf/blob/develop/consurf) (lines 512-517):

```
     $VARS{protein_db} = $config->val( 'databases', 'UNIPROT_DB' );
    # if ($FORM{database} eq "SWISS-PROT"){
    #     $VARS{protein_db} = CONSURF_CONSTANTS::SWISSPROT_DB;}
    # else{
    #     $VARS{protein_db} = CONSURF_CONSTANTS::UNIPROT_DB;}
    # create the seqres fasta file, run blast
```

the default config used by ConSurf is consurfrc.default -> enter the DB in here. (Going to check if it works actually)

```
[databases]
# path to PDB divided. see ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided
PDB_DIVIDED =
# path to Swiss-Prot database. see http://www.uniprot.org/downloads
SWISSPROT_DB=/vagrant/ConSurf_develop/DB/uniprot_sprot.fasta
# path to UniRef90 database. see ftp://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/README
UNIPROT_DB=
RCSB_WGET=wget ftp://ftp.wwpdb.org/pub/pdb/data/structures/all/pdb/
```

CONSURF_CONSTANTS is an additional one, but i do not see, where it is used.

Currently ConSurf is hardcoded to use UNIPROT_DB (~11GBs). I changed

```
$VARS{protein_db} = $config->val( 'databases', 'UNIPROT_DB' );
```

to

```
$VARS{protein_db} = $config->val( 'databases', 'SWISSPROT_DB' );
```

Let's see if it works.

**Comment by juanmirocks** [comment]
I guess this is now solved @GrimSmiler  ?

**Comment by GrimSmiler** [comment]
Yes, i'll document the solution, post it here and close it.

Best Regards, Ilya Migal On вт, янв. 19, 2016 at 11:36 AM, Juan Miguel Cejuela < notifications@github.com [notifications@github.com] > wrote:
I guess this is now solved @GrimSmiler [https://github.com/GrimSmiler] ?

—
Reply to this email directly or view it on GitHub
[https://github.com/Rostlab/ConSurf/issues/8#issuecomment-172812420] .[https://github.com/notifications/beacon/AExpfQua_cUiddr1J_c2b8lk5e0kDDVcks5pbgkUgaJpZM4G9ttq.gif]

**Comment by GrimSmiler** [comment]
Problem:
Running

```
sudo consurf -PDB /vagrant/ConSurf-develop/example/1lk2.pdb -CHAIN A -Out_Dir /vagrant/ConSurf-develop/output_test/ -m
```

the output is

```
ConSurf Version 1.0.6
====================================
Process Started at 12:13:54

Output files could be found in output directory: /vagrant/ConSurf-develop/output_test//
[blastpgp] ERROR: No argument value given for Database

run_blast : run of blast fail. /tmp/mCYRl6c35s//1lk2_A.protein_query.blast is zero or not exists
```

Solution:
Download SwissProt and/or TrEMBLE DBs from [here](http://www.uniprot.org/downloads) in FASTA format.
In configrc.default specify the path to the DBs in `[databases]` section (Ex: SWISSPROT_DB=/home/user/Downloads/uniprot_sprot.fasta)

this will resolve the issue for missing DB

**Comment by juanmirocks** [comment]
@seitza @leidigl see the last DB links, is that useful for you ?
