### ISSUE TITLE
Fix README issues 

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/ConSurf#9]
(For a sample template of the desired README, see: https://github.com/Rostlab/PP2_CS_WS_2015-16/wiki/README.md-Template)
- [x] Write in github description very short description of what this tool does
- [x] Right at the beginning of the README, after the ConSurf title, write a short description and 1-3 important features of the software
- [x] Write who is the tool's author
- [x] Is `bioSequence@tauex.tau.ac.il` the contact person? I thought now it would be the rostlab. In any case, instead of writing an email, refer to the repo issues link.
- ~~[ ] Instructions like "download SwissProt and TrEMBL databases" are very difficult to carry on. Where do I download that from? Which format? ... Same with "format the databases for Blast search" or many other examples. Please always write very simple specific actions for each item, written for a 5 year old.~~
- [x] Provide specific instructions on how to download SWISSPROT or UNIPROT databases
- ~~[x] When you write sth like "update the location of `/biodb/BLAST/Proteins/swissprot`", which file structure are you assuming? You didn't yet tell any instructions or info about the environment.~~ I guess you mean all the locations written in the `CONSURF_CONSTANTS.pm` file. In that case it's all fine :sun_with_face: 
- [x] Where can I download ClustalW exactly from? Put the link and version directly (if one is required or just write latest) in the README. If I go to `ftp://ftp.ebi.ac.uk/pub/software/clustalw2/` I see latest version is now 2.`
- [x] Did you make it run downloading SwissProt and Treml? Is that not too much to ask?
- ~~[ ] I don't fine the file `ConSurf.pl` nor `ConSurf` -- do I have to generate it? -- I only find (`consurf` which points to `ConSurf.pl`)~~
- [x] Be consistent: is it the callable script `consurf` or `ConSurf` or `ConSurf.pl` ? You use these different casings in different examples

**Comment by juanmirocks** [comment]
@GrimSmiler please check remaining issues

**Comment by GrimSmiler** [comment]
Understood. will change update the ReadMe

**Comment by juanmirocks** [comment]
This may be of help for you to document howto download databases. Please double check

https://github.com/Rostlab/SNAP2

**Comment by GrimSmiler** [comment]
added the shell commands to download and unzip the DBs

**Comment by GrimSmiler** [comment]
may i close this issue now?

**Comment by juanmirocks** [comment]
No. I just reviewed the README, and still the issue of different casing for the program persists. Did you commit?

**Comment by GrimSmiler** [comment]
Updated the readme. Now all program calls in code snippets start with consurf. in `cd ConSurf` -> ConSurf is the name of the directory

**Comment by GrimSmiler** [comment]
issue closed?

**Comment by juanmirocks** [comment]
Seems good :+1:
